### ISSUE TITLE
Images (e.g. overlay_psths) can be added to testing workflow summaries for visual confirmation of output

### ISSUE THREAD

**Issue by abuzarmahmood** [katzlabbrandeis/blech_clust#285]
https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/
https://github.com/orgs/community/discussions/101814

**Comment by abuzarmahmood** [comment]
The suggestions and changes made by the agents focus on integrating image generation into the testing workflow and including these images in GitHub Actions job summaries for visual confirmation. Here are the summarized steps and changes:

1. **Identify Relevant Files:**
   - Modify the following files to ensure they generate the necessary images:
     - `blech_units_characteristics.py`: Analyzes neural data and generates plots.
     - `blech_units_plot.py`: Processes neural data and generates plots.
     - `visualize.py`: Provides visualization functions for neural data.

2. **Generate Images in the Code:**
   - Ensure that the scripts generate and save the required images during execution.

3. **Modify GitHub Actions Workflow:**
   - Create or modify a GitHub Actions workflow file to include images in job summaries. If the `.github/workflows` directory is missing, create a new workflow file.

4. **Example Code for Including Images in Job Summaries:**
   - Add the following YAML code to your workflow file to include images in the job summaries:

```yaml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate images
      run: |
        python blech_units_characteristics.py
        python blech_units_plot.py

    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: test-images
        path: path/to/generated/images

    - name: Add images to summary
      run: |
        echo "## Test Images" >> $GITHUB_STEP_SUMMARY
        for img in path/to/generated/images/*; do
          echo "![]($img)" >> $GITHUB_STEP_SUMMARY
        done
```

5. **Ensure Image Paths are Correct:**
   - Verify that the paths to the generated images in the workflow file are correct and accessible.

6. **Test the Workflow:**
   - Test the workflow by pushing a commit or creating a pull request. Check the GitHub Actions tab to ensure images are displayed correctly in the job summary.

By following these steps, you can successfully integrate image generation into the testing workflow and include them in the summaries for visual confirmation.

---
*This response was automatically generated by blech_bot*
