### ISSUE TITLE
Additional commits to a PR should kill previously running GitHub actions before starting a new one

### ISSUE THREAD

**Issue by abuzarmahmood** [katzlabbrandeis/blech_clust#355]

**Comment by abuzarmahmood** [comment]
Apply above edits to GitHub workflow

**Comment by abuzarmahmood** [comment]
The existing workflow file `/home/exouser/Desktop/blech_github_bot/src/repos/katzlabbrandeis/blech_clust/.github/workflows/python_workflow_test.yml` already includes the `concurrency` key for each job, ensuring that only one instance of the workflow runs at a time for a given branch or pull request. This configuration automatically cancels any in-progress runs when a new commit is pushed.

### Suggested Improvements:
1. **Ensure Consistency Across All Jobs**:
   - Verify that all jobs within the workflow have the `concurrency` key set correctly. This is already done in the current file.

2. **Generalize the Workflow for Multiple Branches**:
   - If you want this behavior for multiple branches, ensure the `on` section includes all relevant branches.

3. **Documentation and Comments**:
   - Add comments to explain the purpose of the `concurrency` settings for future maintainers.

### Example Code Snippet:
The current configuration already includes the necessary concurrency settings:
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} <job-name>
  cancel-in-progress: true
```

### No Further Changes Needed:
The current workflow file is already configured to cancel in-progress runs when a new commit is pushed to a pull request. If you need to apply this configuration to other workflows, ensure they include similar `concurrency` settings.

If you have any specific requirements or additional workflows to configure, please let me know. Otherwise, the current setup should meet the needs described in the feedback.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
[ develop_issue ]

**Comment by abuzarmahmood** [comment]
The existing workflow file `python_workflow_test.yml` already includes the `concurrency` key for each job, ensuring that only one instance of the workflow runs at a time for a given branch or pull request. This setup automatically cancels any in-progress runs when a new commit is pushed.

### Suggested Improvements:

1. **Ensure Consistency Across All Jobs**:
   - Verify that all jobs within the workflow have the `concurrency` key set correctly. The current setup seems to have this in place, but it's important to ensure that any new jobs added in the future also include this configuration.

2. **Generalize the Workflow Trigger**:
   - If the workflow should also trigger on pushes to branches other than `pull_request`, consider updating the `on` section to include `push` events. This will ensure that the concurrency control applies to both direct pushes and pull requests.

3. **Documentation and Comments**:
   - Add comments to explain the purpose of the `concurrency` settings, which can be helpful for future maintainers of the workflow.

Here's an example of how you might update the `on` section if you want to include push events:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

These suggestions ensure that the workflow remains efficient and resource-conscious by preventing redundant builds. If the current setup meets your needs, no further changes are necessary.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
Update python_workflow_test.yml so that all the concurrency groups have the same name

**Comment by abuzarmahmood** [comment]
To address the user's feedback about ensuring all concurrency groups have the same name in the `python_workflow_test.yml` file, you can make the following changes:

### Suggested Changes:

1. **Standardize Concurrency Group Names**:
   - Update the `concurrency` group names for all jobs to ensure they are consistent. This involves setting a uniform name for the concurrency group across all jobs.

Here's how you can modify the concurrency settings in the workflow file:

```yaml
jobs:
  Preamble:
    runs-on: self-hosted
    concurrency:
      group: common-concurrency-group
      cancel-in-progress: true
    steps:
      # existing steps

  Spike-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: common-concurrency-group
      cancel-in-progress: true
    steps:
      # existing steps

  EMG-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: common-concurrency-group
      cancel-in-progress: true
    steps:
      # existing steps

  Spike-EMG:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: common-concurrency-group
      cancel-in-progress: true
    steps:
      # existing steps
```

### Explanation:

- **Consistency**: By using a single concurrency group name (`common-concurrency-group`), you ensure that only one instance of the workflow runs at a time across all jobs. This prevents any overlap or conflicts between jobs.
- **Efficiency**: This setup helps in managing resources effectively by avoiding redundant runs.

These changes will ensure that the concurrency control is applied uniformly across all jobs in the workflow. If this meets your requirements, you can proceed with these modifications. If further customization is needed, adjust the group name as per your specific concurrency requirements.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
To address the user's feedback and ensure that all concurrency groups have the same name format, you can update the `concurrency` group names in the `python_workflow_test.yml` file. Here's how you can modify the file:

### Suggested Changes:

1. **Update Concurrency Group Names**:
   - Change the `group` value for each job to use the format `${{ github.workflow }}-${{ github.ref }}`. This ensures consistency across all jobs.

### Specific Code Changes:

Modify the `concurrency` section for each job as follows:

```yaml
jobs:
  Preamble:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # ... (rest of the job configuration)

  Spike-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # ... (rest of the job configuration)

  EMG-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # ... (rest of the job configuration)

  Spike-EMG:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    # ... (rest of the job configuration)
```

### Additional Recommendations:

- **Documentation and Comments**: Consider adding comments to explain the purpose of the `concurrency` settings, which can be helpful for future maintainers of the workflow.

These changes will ensure that all jobs within the workflow use a consistent concurrency group naming convention, as requested by the user. If the current setup meets your needs, no further changes are necessary.

---
*This response was automatically generated by blech_bot*
