### ISSUE TITLE
Update GitHub workflow yml so prefect pipeline explicitly runs in blech_clust conda environment 

### ISSUE THREAD

**Issue by abuzarmahmood** [katzlabbrandeis/blech_clust#367]

**Comment by abuzarmahmood** [comment]
The issue involves updating the GitHub workflow YAML file to ensure that the Prefect pipeline explicitly runs in the `blech_clust` conda environment. The suggested changes focus on modifying the workflow to activate the conda environment before executing the Python scripts. Here's a summary of the suggestions and changes made:

1. **File Identified**: 
   - **File**: `.github/workflows/python_workflow_test.yml`
   - **Description**: This file defines a GitHub Actions workflow for testing Python scripts on a self-hosted runner. It includes jobs for running Prefect pipeline tests for different configurations (Spike-Only, EMG-Only, Spike-EMG).

2. **Suggested Modifications**:
   - **Activate Conda Environment**: Before running the Python scripts in each job, add a step to activate the `blech_clust` conda environment. This can be done by adding a command like `conda activate blech_clust` in the `steps` section of each job.

3. **Specific Changes**:
   - **Spike-Only Job**:
     - **Line**: 036-043
     - **Change**: Add a step to activate the `blech_clust` conda environment before running the Prefect SPIKE only test.
     - **Code Snippet**:
       ```yaml
       - name: Activate conda environment
         shell: bash
         run: source activate blech_clust
       - name: Prefect SPIKE only test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: python pipeline_testing/prefect_pipeline.py -s 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

   - **EMG-Only Job**:
     - **Line**: 050-057
     - **Change**: Add a step to activate the `blech_clust` conda environment before running the Prefect EMG only test.
     - **Code Snippet**:
       ```yaml
       - name: Activate conda environment
         shell: bash
         run: source activate blech_clust
       - name: Prefect EMG only test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: python pipeline_testing/prefect_pipeline.py -e 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

   - **Spike-EMG Job**:
     - **Line**: 064-071
     - **Change**: Add a step to activate the `blech_clust` conda environment before running the Prefect SPIKE then EMG test.
     - **Code Snippet**:
       ```yaml
       - name: Activate conda environment
         shell: bash
         run: source activate blech_clust
       - name: Prefect SPIKE then EMG test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

By implementing these changes, the Prefect pipeline will run within the specified conda environment, ensuring that all dependencies are correctly managed.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
Instead of activating conda before, prepend the python command with "conda run -n blech_clust"

**Comment by abuzarmahmood** [comment]
Based on the user feedback, the suggestion is to prepend the Python command with `conda run -n blech_clust` instead of activating the conda environment separately. Here's how you can modify the GitHub Actions workflow YAML file to incorporate this change:

1. **File Identified**: 
   - **File**: `.github/workflows/python_workflow_test.yml`
   - **Description**: This file defines a GitHub Actions workflow for testing Python scripts on a self-hosted runner. It includes jobs for running Prefect pipeline tests for different configurations (Spike-Only, EMG-Only, Spike-EMG).

2. **Suggested Modifications**:
   - **Use Conda Run**: Prepend the Python command with `conda run -n blech_clust` in the `run` command for each job.

3. **Specific Changes**:
   - **Spike-Only Job**:
     - **Lines**: 037-043
     - **Change**: Modify the `run` command to use `conda run`.
     - **Code Snippet**:
       ```yaml
       - name: Prefect SPIKE only test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -s 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

   - **EMG-Only Job**:
     - **Lines**: 051-057
     - **Change**: Modify the `run` command to use `conda run`.
     - **Code Snippet**:
       ```yaml
       - name: Prefect EMG only test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -e 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

   - **Spike-EMG Job**:
     - **Lines**: 065-071
     - **Change**: Modify the `run` command to use `conda run`.
     - **Code Snippet**:
       ```yaml
       - name: Prefect SPIKE then EMG test
         shell: bash
         working-directory: /home/exouser/Desktop/blech_clust
         run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
           tee ~/Desktop/blech_clust/github.log;
           if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                             then echo "ERROR detected by bash"; exit 1; fi
       ```

By implementing these changes, the Prefect pipeline will run within the specified conda environment using `conda run`, ensuring that all dependencies are correctly managed without the need for a separate activation step.

---
*This response was automatically generated by blech_bot*
