### ISSUE TITLE
In github workflow, run jobs in order spike --> emg --> spike-emg

### ISSUE THREAD

**Issue by abuzarmahmood** [katzlabbrandeis/blech_clust#372]

**Comment by abuzarmahmood** [comment]
The issue at hand involves modifying a GitHub Actions workflow to ensure that jobs are executed in a specific order: Spike → EMG → Spike-EMG. The current setup has all jobs depending on a "Preamble" job, but the desired sequence requires "Spike-Only" to run before "EMG-Only", and "EMG-Only" to run before "Spike-EMG".

### Overview of Plan to Address the Issues:
To achieve the desired job execution order, the `needs` attribute for each job in the workflow YAML file should be adjusted. Specifically:
- The "EMG-Only" job should depend on the "Spike-Only" job.
- The "Spike-EMG" job should depend on the "EMG-Only" job.

### Specific Details of Changes to be Made:

1. **Change the `needs` attribute for the "EMG-Only" job**:
   - **File**: `.github/workflows/python_workflow_test.yml`
   - **Line**: 46
   - **Description of change**: Modify the `needs` attribute for the "EMG-Only" job to depend on the "Spike-Only" job.
   - **Code snippet of edits**:
     ```yaml
     EMG-Only:
       runs-on: self-hosted
       needs: Spike-Only
       concurrency:
         group: ${{ github.workflow }}-${{ github.ref }}
         cancel-in-progress: true
     ```

2. **Change the `needs` attribute for the "Spike-EMG" job**:
   - **File**: `.github/workflows/python_workflow_test.yml`
   - **Line**: 60
   - **Description of change**: Modify the `needs` attribute for the "Spike-EMG" job to depend on the "EMG-Only" job.
   - **Code snippet of edits**:
     ```yaml
     Spike-EMG:
       runs-on: self-hosted
       needs: EMG-Only
       concurrency:
         group: ${{ github.workflow }}-${{ github.ref }}
         cancel-in-progress: true
     ```

These changes will ensure that the jobs are executed in the specified order: Spike → EMG → Spike-EMG.

---
*This response was automatically generated by blech_bot*
