### ISSUE TITLE
Remove spike-only test for prefect_pipeline and github workflow yaml

### ISSUE THREAD

**Issue by abuzarmahmood** [katzlabbrandeis/blech_clust#418]
Keep the implementation, just remove it's call from the github workflow, and from the `all` pipeline in `prefect_pipeline.py`
It is not very useful to test spike-sorting with no emg channels, when we're already testing it with both electodes+emg

**Comment by abuzarmahmood** [comment]
The issue involves removing a spike-only test from both the Prefect pipeline and the GitHub workflow YAML files in the `katzlabbrandeis/blech_clust` repository. The spike-only test is considered redundant because spike-sorting is already tested with both electrodes and EMG channels.

### Suggestions and Changes Made:

1. **File Identification:**
   - **File:** `/home/exouser/Desktop/blech_github_bot/src/repos/katzlabbrandeis/blech_clust/pipeline_testing/prefect_pipeline.py`
     - **Description:** This file likely contains the implementation of the `all` pipeline in `prefect_pipeline.py`. The spike-only test call needs to be removed from this pipeline.
   - **File:** `.github/workflows`
     - **Description:** The spike-only test call needs to be removed from the GitHub workflow YAML files. The specific file containing the spike-only test call was not found, so manual inspection of the YAML files in the `.github/workflows` directory is necessary.

2. **Specific Changes:**
   - **Remove Spike-Only Test from `prefect_pipeline.py`:**
     - **Lines:** 670-678
     - **Description:** Remove the call to `spike_only_test()` from the `full_test()` function, which is part of the `all` pipeline.
     - **Code Snippet:**
       ```python
       @flow(log_prints=True)
       def full_test():
           if break_bool:
               # spike_only_test()  # Remove this line
               emg_only_test()
               spike_emg_test()
           else:
               try:
                   # spike_only_test()  # Remove this line
               except:
                   print('Failed to run spike test')
               try:
                   emg_only_test()
               except:
                   print('Failed to run emg test')
               try:
                   spike_emg_test()
               except:
                   print('Failed to run spike+emg test')
       ```

   - **Remove Spike-Only Test from GitHub Workflow:**
     - **Description:** Locate the YAML file that contains the spike-only test call and remove it. Look for any lines that trigger the spike-only test and delete them.

By implementing these changes, the unnecessary spike-only test will be removed from both the Prefect pipeline and the GitHub workflow, aligning with the user's request.

---
*This response was automatically generated by blech_bot using model gpt-4o*

**Comment by abuzarmahmood** [comment]
Suggest concrete changes to the GitHub workflow file

**Comment by abuzarmahmood** [comment]
To address the feedback and suggest concrete changes to the GitHub workflow file, you need to remove the sections related to the spike-only test. Here are the specific changes you can make to the `python_workflow_test.yml` file located at `/home/exouser/Desktop/blech_github_bot/src/repos/katzlabbrandeis/blech_clust/.github/workflows/python_workflow_test.yml`:

### Suggested Changes:

1. **Remove the `Spike-Only-Install` Job:**
   - **Lines to Remove:** 70-85
   - **Description:** This job tests the spike sorting pipeline in isolation during the installation phase. Since the spike-only test is redundant, this section should be removed.
   - **Code to Remove:**
     ```yaml
     Spike-Only-Install:
       runs-on: self-hosted
       needs: Install
       concurrency:
         group: ${{ github.workflow }}-${{ github.ref }}
         cancel-in-progress: true
       # Test spike sorting pipeline in isolation
       if: ${{ contains(github.event.pull_request.labels.*.name, 'install') }}
       steps:
         - name: Prefect SPIKE only test
           shell: bash
           working-directory: /home/exouser/Desktop/blech_clust
           run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -s 2>&1 |
             tee ~/Desktop/blech_clust/github.log;
             if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                               then echo "ERROR detected by bash"; exit 1; fi
     ```

2. **Remove the `Spike-Only` Job:**
   - **Lines to Remove:** 117-132
   - **Description:** This job tests the spike sorting pipeline in isolation outside the installation phase. It should also be removed for the same reason.
   - **Code to Remove:**
     ```yaml
     Spike-Only:
       runs-on: self-hosted
       needs: Preamble
       concurrency:
         group: ${{ github.workflow }}-${{ github.ref }}
         cancel-in-progress: true
       # Test spike sorting pipeline in isolation
       if: ${{ !contains(github.event.pull_request.labels.*.name, 'install') }}
       steps:
         - name: Prefect SPIKE only test
           shell: bash
           working-directory: /home/exouser/Desktop/blech_clust
           run: conda run -n blech_clust python pipeline_testing/prefect_pipeline.py -s 2>&1 |
             tee ~/Desktop/blech_clust/github.log;
             if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                               then echo "ERROR detected by bash"; exit 1; fi
     ```

By removing these sections, the GitHub workflow will no longer run the redundant spike-only tests, aligning with the user's request to streamline the testing process.

---
*This response was automatically generated by blech_bot using model gpt-4o*
